# Generated by Django 5.0.1 on 2024-01-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='鄉鎮')),
                ('zip_code', models.CharField(max_length=30, verbose_name='郵遞區號')),
                ('district_court', models.CharField(max_length=30, verbose_name='地方法院')),
                ('land_office', models.CharField(max_length=30, verbose_name='地政事務所')),
                ('finance_and_tax_bureau', models.CharField(max_length=30, verbose_name='財政稅務局')),
                ('police_station', models.CharField(max_length=30, verbose_name='警察局')),
                ('irs', models.CharField(max_length=30, verbose_name='國稅局')),
                ('home_office', models.CharField(max_length=30, verbose_name='戶政事務所')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Yfcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yfcaseCaseNumber', models.CharField(max_length=100, verbose_name='案號(*)')),
                ('yfcaseCompany', models.CharField(blank=True, max_length=50, null=True, verbose_name='所屬公司')),
                ('yfcaseBigSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='段號')),
                ('yfcaseSmallSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='小段')),
                ('yfcaseVillage', models.CharField(blank=True, max_length=100, null=True, verbose_name='村里')),
                ('yfcaseNeighbor', models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰')),
                ('yfcaseStreet', models.CharField(blank=True, max_length=100, null=True, verbose_name='街路')),
                ('yfcaseSection', models.CharField(blank=True, max_length=100, null=True, verbose_name='段')),
                ('yfcaseLane', models.CharField(blank=True, max_length=100, null=True, verbose_name='巷')),
                ('yfcaseAlley', models.CharField(blank=True, max_length=100, null=True, verbose_name='弄')),
                ('yfcaseNumber', models.CharField(max_length=100, null=True, verbose_name='號')),
                ('yfcaseFloor', models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)')),
                ('yfcaseCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='縣市')),
                ('yfcaseTownship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.township', verbose_name='鄉鎮區里')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='姓名')),
                ('is_Coowner', models.BooleanField(default=False, verbose_name='共有人一致')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='app.yfcase')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landNumber', models.CharField(max_length=100, null=True, verbose_name='地號')),
                ('landUrl', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('landArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='地坪(平方公尺)')),
                ('landHoldingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分')),
                ('landHoldingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分')),
                ('landRemark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備註')),
                ('landUpdated', models.DateTimeField(auto_now=True, verbose_name='案件最後更新時間')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='app.yfcase')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildNumber', models.CharField(max_length=100, null=True, verbose_name='建號')),
                ('buildUrl', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('buildArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='建坪(平方公尺)')),
                ('buildHoldingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分')),
                ('buildHoldingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分')),
                ('buildTypeUse', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物型')),
                ('buildUsePartition', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用分區')),
                ('buildRemark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備註')),
                ('buildAncillaryBuildingUseBy', models.CharField(blank=True, max_length=100, null=True, verbose_name='附屬建物用途')),
                ('buildAncillaryBuildingArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='附屬建物面積')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='app.yfcase')),
            ],
        ),
    ]
