# Generated by Django 5.0.1 on 2024-01-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yfcase_yfcasecasestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
