# Generated by Django 5.0.1 on 2024-01-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseTownship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鄉鎮區里'),
        ),
    ]
